from datetime import datetime

def generate_report(workflow):

    report = f"""
==============================
 CloudGuard AI Incident Report
==============================

Generated:
{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

Scenario:
{workflow["reasoning"]["scenario"]}

Risk:
{workflow["metrics"]["risk"]}

Root Cause:
{workflow["root_cause"]}

Recovery Plan:
"""

    for step in workflow["plan"]:
        report += f"\n- {step}"

    report += f"""

Action Taken:
{workflow["action"]["action"]}

Execution Status:
{workflow["action"]["status"]}

Generated by CloudGuard AI v4.0
"""

    return report